'use client';
import {useEffect,useState} from 'react';import type {Attempt} from '@/lib/types';import ResultReview from './result-review';
const classes=['Righteousness Class','Peace Class','Joy'];
export default function AssessmentApp(){const [attempt,setAttempt]=useState<Attempt|null>(null),[result,setResult]=useState<any>(null),[name,setName]=useState(''),[className,setClass]=useState(classes[0]),[other,setOther]=useState(''),[index,setIndex]=useState(0),[remaining,setRemaining]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const token=localStorage.getItem('how_attempt_token');if(token)request('attempts/result',{token}).then(setResult).catch(()=>{})},[]);
 useEffect(()=>{if(!attempt?.deadlineAt||attempt.status!=='in_progress')return;const tick=()=>{const n=Math.max(0,Math.ceil((new Date(attempt.deadlineAt!).getTime()-Date.now())/1000));setRemaining(n);if(n===0)submit(true)};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[attempt?.deadlineAt,attempt?.status]);
 async function request(path:string,body:any){const r=await fetch('/api/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}
 async function start(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const a=await request('attempts/start',{studentName:name,className:className==='Other'?other:className});localStorage.setItem('how_attempt_token',a.token);setAttempt(a)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function answer(aq:string,option:string){if(!attempt)return;setAttempt({...attempt,answers:{...attempt.answers,[aq]:option}});try{await request('attempts/save',{token:attempt.token,attemptQuestionId:aq,selectedOptionId:option})}catch(e:any){setError('Answer is shown locally but could not be saved. '+e.message)}}
 async function submit(auto=false){if(!attempt||busy)return;if(!auto&&Object.keys(attempt.answers).length<attempt.questions.length&&!confirm('Some questions are unanswered. Submit anyway?'))return;if(!auto&&!confirm('You are about to submit your assessment. You will not be able to change your answers after submission.'))return;setBusy(true);try{await request('attempts/submit',{token:attempt.token});setResult(await request('attempts/result',{token:attempt.token}));setAttempt({...attempt,status:'submitted'})}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(result)return <section className="resultPage"><div className="card narrow"><h2>Assessment Completed</h2><p>Thank you, {result.studentName}. Your answers have been saved.</p><div className="stats"><div className="stat"><span>Score</span><strong>{result.correctCount}/{result.totalQuestions}</strong></div><div className="stat"><span>Percentage</span><strong>{result.percentage}%</strong></div><div className="stat"><span>Standing</span><strong>{result.standing}</strong></div></div>{result.autoSubmitted&&<p className="muted">The time limit was reached, so the assessment was submitted automatically.</p>}</div><ResultReview result={result}/></section>;
 if(!attempt)return <form className="card narrow" onSubmit={start}><h2>Participant details</h2><label htmlFor="name">Full name</label><input id="name" value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={100} required/><label htmlFor="class">Class name</label><select id="class" value={className} onChange={e=>setClass(e.target.value)}>{classes.map(c=><option key={c}>{c}</option>)}<option>Other</option></select>{className==='Other'&&<><label htmlFor="other">Other class</label><input id="other" value={other} onChange={e=>setOther(e.target.value)} required maxLength={80}/></>}<p className="muted">Your timer starts when you select Start Assessment.</p>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy}>{busy?'Starting…':'Start Assessment'}</button></form>;
 const q=attempt.questions[index],answered=Object.keys(attempt.answers).length,fmt=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`;
 return <section className="card"><div className="row wrap"><div><strong>{attempt.studentName}</strong><div className="muted">{attempt.className} · {answered}/{attempt.questions.length} answered</div></div>{remaining!==null&&<div className={'timer '+(remaining<300?'danger':'')} aria-live="polite">Time left {fmt(remaining)}</div>}</div><hr/><p className="muted">Question {index+1} of {attempt.questions.length}</p><h2>{q.question}</h2>{q.options.map((o,i)=><label className="option" key={o.id}><input type="radio" name={q.attemptQuestionId} checked={attempt.answers[q.attemptQuestionId]===o.id} onChange={()=>answer(q.attemptQuestionId,o.id)}/><span><strong>{String.fromCharCode(65+i)}.</strong> {o.option_text}</span></label>)}<div className="nav">{attempt.questions.map((x,i)=><button type="button" aria-label={`Question ${i+1}`} className={(i===index?'current ':'')+(attempt.answers[x.attemptQuestionId]?'done':'')} onClick={()=>setIndex(i)} key={x.attemptQuestionId}>{i+1}</button>)}</div>{error&&<p className="error">{error}</p>}<div className="row"><button className="secondary" disabled={index===0} onClick={()=>setIndex(index-1)}>Previous</button>{index<attempt.questions.length-1?<button onClick={()=>setIndex(index+1)}>Next</button>:<button disabled={busy} onClick={()=>submit(false)}>Submit assessment</button>}</div></section>}
